### ISSUE TITLE
Create invoice PDF (Ruben Brinkman)

### ISSUE THREAD

**Issue by GEWISabc** [GEWIS/sudosos-backend#13]
When an invoice has been made a PDF for said invoice should be created on the BE.

- [ ] Create PDF
- [ ] Get PDF

**Comment by Yoronex** [comment]
@JustSamuel Gijs has finished the generic GEWIS PDF generator. (https://github.com/GEWIS/PDF-server) It exposes an API that simply returns a generated file according to the input. Do you want to implement this (because you are familiar with the invoicing system) as a separate module (because it requires this image in the docker-compose stack), or should I do it?

**Comment by JustSamuel** [comment]
This seems to be quite blocking, so I'll focus on this for now.
