### ISSUE TITLE
[BUG] Pagination returns 200 OK when not everything is OK

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-backend#267]
### Current behavior

Whenever the backend returns a paginated response, the status will be 200, even though not all parameters are succesfully handled. For example, try to get more than 500 users, and only silently there will be only 500 results returned.

### Desired behavior

In this situation, I expected a different response code. This could be a 400 Bad Request, but that is kind of harsh. Maybe 206 partial content, but that is not exactly within normally used standards.

### Steps to reproduce

Do a request on the Swagger with take parameter more than 500, observe the 200 OK.

**Comment by Yoronex** [comment]
By design, there is a maximum limit on the amount of entries one can request using pagination. Indeed, when you request 1000 records, you will ever only get at most 500. The _actual_ amount of records used by the backend is also correctly reflected in the `_pagination` object, namely the used `skip` and `take`.

Therefore, I am not really convinced whether we should change the current pagination behaviour, as the backend is not doing anything it is not telling you.

**Comment by JustSamuel** [comment]
Closed since I agree with @Yoronex and no response was given.
